#!/bin/bash
TMP=$(mktemp -d --suffix=HUNTER)
PRE_KSS=$(cat PRE_KSS)
POST_KSS=$(cat POST_KSS)
x=$(cat LOWER_NUM)
END=$(cat UPPER_NUM)
echo HOSTNAME,PINGS0=yes/2=no,IP,PTR > $TMP/diggit.csv
cp onehunt $TMP/onehunt
while [ $x -le $END ]
do
    THIS_NUM=$(printf "%03d" $x)
    THIS_NAME=$(echo $PRE_KSS$THIS_NUM$POST_KSS)
    echo "./onehunt $THIS_NAME >>$TMP/diggit.csv" >> $TMP/working.sh
      x=$(( $x + 1 ))
done

/usr/bin/time parallel --jobs 100 -- < $TMP/working.sh
cp $TMP/diggit.csv ./para-diggit.csv
rm -Rf $TMP
